s3:
  buckets: 
    inputs: ''
    inputs_dest: ''
    objectives: ''
    objectives_dest: ''
    data: ''
    data_dest: ''
    solutions: ''
  aws_secret_access_key: ''
  aws_access_key_id: ''
  region: ''
  cloud_service_provider: 'aws'